name: Daily Docker Image Autobuild

on:
  schedule:
    - cron:  '11 0 * * *'
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login

    steps:
    - uses: actions/checkout@v2
    - name: Initialization
      run: docker login -u $username -p $password
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push the Docker image
      run: make all
      
