name: Daily Docker Image Autobuild

on:
  schedule:
    - cron:  '11 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialization
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Login
      run: docker login -u $username -p $password
    - name: Build and Push the Docker image
      run: make all
