name: Daily Docker Image Autobuild

on:
  schedule:
    - cron:  '11 0 * * *'
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest
    
    if: github.actor == github.event.repository.owner.login

    steps:
    - uses: actions/checkout@v2
#     - name: Login to docker hub
#       uses: actions-hub/docker/login@master
#       env:
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push the Docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        make all
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
